global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'trace'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['trace:8080']
        labels:
          service: 'trace'

  - job_name: 'relay'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['relay:9467']
        labels:
          service: 'relay'

  - job_name: 'billing'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['billing:8080']
        labels:
          service: 'billing'

  - job_name: 'simulator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['simulator:9468']
        labels:
          service: 'simulator'
