replicaCount: 1

image:
  repository: ghcr.io/laststate/billing-service
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  dbURL: ""
  traceURL: "http://trace:8080"
  stripeKey: ""
  mpKey: ""
  cryptoKey: ""
  stripeWebhookSecret: ""
  mpWebhookSecret: ""
  cryptoWebhookSecret: ""
  port: "8080"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: billing.laststate.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
